<?php
/**
 * Created by PhpStorm.
 * User: ioulai2017
 * Date: 17/07/2018
 * Time: 10:35
 */

namespace App\Service;


class Services
{
    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}