<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\FileUploader' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Service\\FileUploader.php';

return $this->services['App\Service\FileUploader'] = new \App\Service\FileUploader(($this->targetDirs[3].'/public/ressources/img'));
