<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLisputf\src-prodDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLisputf/src-prodDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLisputf.legacy');

    return;
}

if (!\class_exists(src-prodDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLisputf\src-prodDebugProjectContainer::class, src-prodDebugProjectContainer::class, false);
}

return new \ContainerLisputf\src-prodDebugProjectContainer(array(
    'container.build_hash' => 'Lisputf',
    'container.build_id' => '62c82477',
    'container.build_time' => 1531994674,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerLisputf');
