<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOw2plnx\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOw2plnx/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOw2plnx.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerOw2plnx\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerOw2plnx\srcProdProjectContainer(array(
    'container.build_hash' => 'Ow2plnx',
    'container.build_id' => 'c8a8d02b',
    'container.build_time' => 1531995583,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOw2plnx');
