<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\FlightController:liste_vols' => function () {
    return ${($_ = isset($this->services['service_locator.suqkrkj']) ? $this->services['service_locator.suqkrkj'] : $this->load('getServiceLocator_SuqkrkjService.php')) && false ?: '_'};
}, 'App\\Controller\\FlightController:proposer_vol' => function () {
    return ${($_ = isset($this->services['service_locator.j_3zsuk']) ? $this->services['service_locator.j_3zsuk'] : $this->load('getServiceLocator_J3zsukService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController:home' => function () {
    return ${($_ = isset($this->services['service_locator.otnedf2']) ? $this->services['service_locator.otnedf2'] : $this->load('getServiceLocator_Otnedf2Service.php')) && false ?: '_'};
}, 'App\\Controller\\ReservationController:reservation' => function () {
    return ${($_ = isset($this->services['service_locator..c9ywdv']) ? $this->services['service_locator..c9ywdv'] : $this->load('getServiceLocator__C9ywdvService.php')) && false ?: '_'};
}, 'App\\Controller\\ReservationController:reservation_modif' => function () {
    return ${($_ = isset($this->services['service_locator.ggxa2t1']) ? $this->services['service_locator.ggxa2t1'] : $this->load('getServiceLocator_Ggxa2t1Service.php')) && false ?: '_'};
}, 'App\\Controller\\ReservationController:reservation_user' => function () {
    return ${($_ = isset($this->services['service_locator.ggxa2t1']) ? $this->services['service_locator.ggxa2t1'] : $this->load('getServiceLocator_Ggxa2t1Service.php')) && false ?: '_'};
}, 'App\\Controller\\UserController:login' => function () {
    return ${($_ = isset($this->services['service_locator.bmygemm']) ? $this->services['service_locator.bmygemm'] : $this->load('getServiceLocator_BmygemmService.php')) && false ?: '_'};
}, 'App\\Controller\\UserController:register' => function () {
    return ${($_ = isset($this->services['service_locator.mbm0w9h']) ? $this->services['service_locator.mbm0w9h'] : $this->load('getServiceLocator_Mbm0w9hService.php')) && false ?: '_'};
}, 'App\\Controller\\FlightController::liste_vols' => function () {
    return ${($_ = isset($this->services['service_locator.suqkrkj']) ? $this->services['service_locator.suqkrkj'] : $this->load('getServiceLocator_SuqkrkjService.php')) && false ?: '_'};
}, 'App\\Controller\\FlightController::proposer_vol' => function () {
    return ${($_ = isset($this->services['service_locator.j_3zsuk']) ? $this->services['service_locator.j_3zsuk'] : $this->load('getServiceLocator_J3zsukService.php')) && false ?: '_'};
}, 'App\\Controller\\MainController::home' => function () {
    return ${($_ = isset($this->services['service_locator.otnedf2']) ? $this->services['service_locator.otnedf2'] : $this->load('getServiceLocator_Otnedf2Service.php')) && false ?: '_'};
}, 'App\\Controller\\ReservationController::reservation' => function () {
    return ${($_ = isset($this->services['service_locator..c9ywdv']) ? $this->services['service_locator..c9ywdv'] : $this->load('getServiceLocator__C9ywdvService.php')) && false ?: '_'};
}, 'App\\Controller\\ReservationController::reservation_modif' => function () {
    return ${($_ = isset($this->services['service_locator.ggxa2t1']) ? $this->services['service_locator.ggxa2t1'] : $this->load('getServiceLocator_Ggxa2t1Service.php')) && false ?: '_'};
}, 'App\\Controller\\ReservationController::reservation_user' => function () {
    return ${($_ = isset($this->services['service_locator.ggxa2t1']) ? $this->services['service_locator.ggxa2t1'] : $this->load('getServiceLocator_Ggxa2t1Service.php')) && false ?: '_'};
}, 'App\\Controller\\UserController::login' => function () {
    return ${($_ = isset($this->services['service_locator.bmygemm']) ? $this->services['service_locator.bmygemm'] : $this->load('getServiceLocator_BmygemmService.php')) && false ?: '_'};
}, 'App\\Controller\\UserController::register' => function () {
    return ${($_ = isset($this->services['service_locator.mbm0w9h']) ? $this->services['service_locator.mbm0w9h'] : $this->load('getServiceLocator_Mbm0w9hService.php')) && false ?: '_'};
})));
