<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.j_3zsuk' shared service.

return $this->services['service_locator.j_3zsuk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('em' => function () {
    return ${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'};
}, 'fileUploader' => function () {
    $f = function (\App\Service\FileUploader $v = null) { return $v; }; return $f(${($_ = isset($this->services['App\Service\FileUploader']) ? $this->services['App\Service\FileUploader'] : $this->services['App\Service\FileUploader'] = new \App\Service\FileUploader(($this->targetDirs[3].'/public/ressources/img'))) && false ?: '_'});
}));
