<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdnmkjx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdnmkjx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYdnmkjx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYdnmkjx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerYdnmkjx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ydnmkjx',
    'container.build_id' => '069d83c9',
    'container.build_time' => 1531995483,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdnmkjx');
